// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Instagram/LinkedIn/Twitter in-app browsers throw a SecurityError when code
// touches localStorage. Fall back to an in-memory store so the Supabase client
// initialises cleanly and all public queries work without auth.
const safeStorage = (() => {
  try {
    localStorage.setItem("__sb_test__", "1");
    localStorage.removeItem("__sb_test__");
    return localStorage;
  } catch {
    const mem = new Map<string, string>();
    return {
      getItem:    (k: string) => mem.get(k) ?? null,
      setItem:    (k: string, v: string) => { mem.set(k, v); },
      removeItem: (k: string) => { mem.delete(k); },
    };
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});